# @package _global_

model:
  _target_: starter_kit.models.segformer.SegFormerModel
  n_epochs: ${n_epochs}
  learning_rate: ${learning_rate}
  early_stop_patience: ${early_stop_patience}
  weight_decay: 0.05
  best_threshold: 0.999
  use_amp: true
  grad_clip: 1.0
  warmup_epochs: 2
  scheduler: cosine
  eta_min_ratio: 0.01
  compile_model: false

network:
  _target_: starter_kit.models.segformer.GeoSegFormer
  mit_variant: b2
  pretrained: true
  use_rh: true
  normalization_path: data/stats/normalization_rh_aux0.json
