# @package _global_

model:
  _target_: starter_kit.models.unet.UNetModel
  n_epochs: ${n_epochs}
  learning_rate: ${learning_rate}
  weight_decay: 1e-5
  best_threshold: 0.99
  log_csv: true
  lr_patience: ${lr_patience}
  lr_factor: ${lr_factor}
  early_stop_patience: ${early_stop_patience}
  mixed_precision: ${mixed_precision}

network:
  _target_: starter_kit.models.unet.UNetwork
  input_dim: 30
  base_channels: 32
  depth: 3
  use_rh: false
  use_wind: false
  n_auxiliary_fields: 2
  normalisation_path: null
