# @package _global_

# GeoUNet wide + per-level RH and potential temperature.

defaults:
  - override /model: geounet

exp_name: geounet_wide_rh_theta
learning_rate: 3e-4
n_epochs: 50
batch_size: 64
early_stop_patience: null

network:
  base_dim: 128
  use_rh: true
  use_theta: true
  normalisation_path: data/stats/normalization_rh_aux0.json
