# @package _global_

defaults:
  - override /model: segformer

exp_name: segformer_b0_rh
learning_rate: 6e-5
n_epochs: 40
batch_size: 64

network:
  mit_variant: b0
  pretrained: true
  use_rh: true
  normalisation_path: data/stats/normalization_rh_aux0.json
