# @package _global_

defaults:
  - override /model: segformer

exp_name: segformer_b2_rh_scratch
learning_rate: 3e-4
n_epochs: 40
batch_size: 32

network:
  mit_variant: b2
  pretrained: false
  use_rh: true
  normalisation_path: data/stats/normalization_rh_aux0.json
