# @package _global_

defaults:
  - override /model: unet

exp_name: unet_brute_wide_aux5
learning_rate: 0.001
batch_size: 32
mixed_precision: true

network:
  use_rh: true
  input_dim: 40           # 28 raw + 7 RH + 5 aux
  base_channels: 64
  depth: 3
  n_auxiliary_fields: 5
  normalisation_path: data/stats/normalization_rh_aux5.json
